title: Service
seo:
  page_description:
  canonical_url:
  featured_image:
  featured_image_alt:
  author_twitter_handle:
  open_graph_type:
  no_index: false

content_blocks:
  - _block_name: section/breadcrumbs
    status: true
    title: About us
    background_image: /images/bg-breadcrumb.png
    

  # Service item section default if Menu page
  - _block_name: service/item
    status: true
    background_color: '#FFFFFF'
    background_image:
    is_reverse: false
    is_hot: true
    is_show_switch_price: true
    image: /images/service4.jpeg
    image_alt: Alt Img
    title: Manicure
    description_simple: This is this description
    list_service:
      - label: Full Set
        price: $50
        description_simple: This is this description
      - label: Full Set - Pink & White with Ombre
        price: $65
        description_simple: This is this description
      - label: Fill-in, Pink & White
        price: $45
        description_simple: This is this description
      - label: Fill-in, Pink only
        price: $30
        description_simple:
      - label: Fill-in, Pink only
        price: $30
        description_simple:
    second_cat:
      - title: REFILL
        description_simple:
        list_service:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
        third_cat:
          - title: REFILL last
            description_simple:
            list_service:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
  - _block_name: service/item
    status: true
    background_color: '#FFFFFF'
    background_image:
    is_reverse: true
    is_hot: true
    is_show_switch_price: true
    image: /images/service5.jpeg
    image_alt: Alt Img
    title: Pedicure
    description_simple: This is this description
    list_service:
      - label: Full Set
        price: $50
        description_simple: This is this description
      - label: Full Set - Pink & White with Ombre
        price: $65
        description_simple: This is this description
      - label: Fill-in, Pink & White
        price: $45
        description_simple: This is this description
      - label: Fill-in, Pink only
        price: $30
        description_simple:
      - label: Fill-in, Pink only
        price: $30
        description_simple:
    second_cat:
      - title: REFILL
        description_simple:
        list_service:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
        third_cat:
          - title: REFILL last
            description_simple:
            list_service:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
  - _block_name: service/item
    status: true
    background_color: '#FFFFFF'
    background_image:
    is_reverse: false
    is_hot: true
    is_show_switch_price: true
    image: /images/service7.jpeg
    image_alt: Alt Img
    title: Kid Service
    description_simple: This is this description
    list_service:
      - label: Full Set
        price: $50
        description_simple: This is this description
      - label: Full Set - Pink & White with Ombre
        price: $65
        description_simple: This is this description
      - label: Fill-in, Pink & White
        price: $45
        description_simple: This is this description
      - label: Fill-in, Pink only
        price: $30
        description_simple:
      - label: Fill-in, Pink only
        price: $30
        description_simple:
    second_cat:
      - title: REFILL
        description_simple:
        list_service:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
        third_cat:
          - title: REFILL last
            description_simple:
            list_service:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
  - _block_name: service/item
    status: true
    background_color: '#FFFFFF'
    background_image:
    is_reverse: true
    is_hot: true
    is_show_switch_price: true
    image: /images/service8.jpeg
    image_alt: Alt Img
    title: Waxing
    description_simple: This is this description
    list_service:
      - label: Full Set
        price: $50
        description_simple: This is this description
      - label: Full Set - Pink & White with Ombre
        price: $65
        description_simple: This is this description
      - label: Fill-in, Pink & White
        price: $45
        description_simple: This is this description
      - label: Fill-in, Pink only
        price: $30
        description_simple:
      - label: Fill-in, Pink only
        price: $30
        description_simple:
    second_cat:
      - title: REFILL
        description_simple:
        list_service:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
          - label: PINK FILL IN
            price: $25
            description_simple:
        third_cat:
          - title: REFILL last
            description_simple:
            list_service:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:
              - label: PINK FILL IN LAST
                price: $45
                description_simple:

  - _block_name: service/switchprice
    status: false
    background_color: '#ffffff'
    background_image: ''
    content: lorem-ipsum
    button:
      background_color: '#efefef'
      border_width: '2'
      border_style: 'solid'
      border_color: '#000000'
      border_radius: '4'
      color: '#000000'